# Generated by Django 5.0.6 on 2024-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pasport_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
