# Generated by Django 5.0.6 on 2024-05-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immovables',
            name='responsuser',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='responsuser',
        ),
        migrations.AddField(
            model_name='discount',
            name='key',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='immovables',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
