# Generated by Django 5.0.6 on 2024-05-26 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0002_alter_requestid_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='UserName',
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время комментария'),
        ),
    ]
