# Generated by Django 5.0.6 on 2024-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0003_alter_discount_uncost'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
