# Generated by Django 5.0.6 on 2024-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancion',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость услуг'),
        ),
    ]
