# Generated by Django 5.0.6 on 2024-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0004_new_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/banners/')),
                ('link', models.URLField()),
            ],
        ),
    ]
