# Generated by Django 5.0.6 on 2024-05-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0005_vacancion_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameField(
            model_name='requestid',
            old_name='User',
            new_name='user',
        ),
    ]
