# Generated by Django 5.0.6 on 2024-09-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='immovables',
            name='media',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='media',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
