# Generated by Django 5.0.6 on 2024-10-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0006_immovables_media_rent_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immovables',
            old_name='media',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='media',
            new_name='img',
        ),
    ]
