# Generated by Django 5.0.6 on 2024-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealtorBack', '0007_rename_media_immovables_img_rename_media_rent_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immovables',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
